timeout: 3600s

substitutions:
  _IMAGE_TAG: "latest"

steps:
- id: airflow-two
  name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "us.gcr.io/$PROJECT_ID/docker-airflow-two:${_IMAGE_TAG}", "."]
  dir: airflow_two/
  waitFor: ['-']

- id: airflow-two-test
  name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "us.gcr.io/$PROJECT_ID/docker-airflow-two-test:${_IMAGE_TAG}", "."]
  dir: airflow_two_test/
  waitFor:
    - airflow-two

- id: airflow-two-upgrade
  name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "us.gcr.io/$PROJECT_ID/docker-airflow-two-upgrade:${_IMAGE_TAG}", "."]
  dir: airflow_two_upgrade/
  waitFor: ['-']

- id: airflow-two-upgrade-test
  name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "us.gcr.io/$PROJECT_ID/docker-airflow-two-upgrade-test:${_IMAGE_TAG}", "."]
  dir: airflow_two_upgrade_test/
  waitFor:
    - airflow-two-upgrade

logsBucket: fathom-containers-cloud-build-logs-36tugmiz

images:
  - us.gcr.io/$PROJECT_ID/docker-airflow-two:${_IMAGE_TAG}
  - us.gcr.io/$PROJECT_ID/docker-airflow-two-test:${_IMAGE_TAG}
  - us.gcr.io/$PROJECT_ID/docker-airflow-two-upgrade:${_IMAGE_TAG}
  - us.gcr.io/$PROJECT_ID/docker-airflow-two-upgrade-test:${_IMAGE_TAG}
