version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  build-arm:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    working_directory: ~/docker-airflow
    steps:
      - checkout
      - run:
          name: Setup Google Cloud Credentials
          working_directory: ~/
          command: echo $CIRCLECI_GCP_SA_KEY > ~/google-auth.json

      - run:
          name: gcr.io docker login
          command: docker login -u _json_key -p "$(cat ~/google-auth.json)" https://us.gcr.io

      - run: ./build_arm.sh all
      - slack/status:
          mentions: "SG7F1S1MZ"
          fail_only: true
          webhook: ${SLACK_ALERTS_WEBHOOK}
          only_for_branches: "master"

workflows:
  version: 2
  build-arm:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ "build-arm-trigger", << pipeline.schedule.name >> ]
    jobs:
      - build-arm
